menu.title=-------Login Program-------
menu.option1=1. Vietnamese
menu.option2=2. English
menu.option3=3. Exit
menu.choice=Moi chon 1 chuc nang:

input.account=So tai khoan:
input.password=Mat khau:
input.captcha=Nhap 1 ky tu captcha:

show.captcha=Captcha: {0}

error.account=So tai khoan phai la 1 so va phai co 10 chu so
error.password=Mat khau phai trong khoang 8-31 ky tu va phai chua ky tu va so
error.captcha=Captcha sai

login.success=Dang nhap thanh cong
